[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "npm run build" # optional

# Redirect /.netlify/functions/* to local functions during local dev (Netlify CLI handles)
